server:
  port: 8000
  ssl:
    enabled: false
  tomcat:
    accesslog:
      enabled: false

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/nuclear_base"
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "root"

nuclear:
  logging:
    request-response:
      enabled: true
    operation-log:
      enabled: true
    jooq:
      enabled: true
